---
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading_journal
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/trading_journal"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
